# Generated by Django 3.0.2 on 2020-02-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200205_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='defaut.jpg', upload_to='profile_pics'),
        ),
    ]
